language: node_js
dist: xenial
os:
  - linux
  - osx
node_js:
  - "8.11.3"
  - "8"
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
cache:
  yarn: true
install:
  - yarn install
  - cd embark-ui && yarn install && cd ..
  - git status && test -z "$(git status --porcelain)"
addons:
    apt:
        packages:
          - build-essential
          - libudev-dev
          - libusb-1.0-0-dev
script:
   - npm run build:node
   - npm test
